{
  "version": "1.3.0",
  "created": "2025-10-29T07:11:43.727Z",
  "registry": {
    "local": "./.citadel/registry",
    "global": "https://registry.syndicate.example.com"
  },
  "performance": {
    "cacheSize": 1000,
    "compression": "zstd",
    "parallelResolution": true
  },
  "governance": {
    "autoEnforce": true,
    "monitoring": true,
    "alerts": true
  }
}