# bun.yaml - Syndicate GOV Config + API Routing Citadel
catalog:
  react: "18.3.1"
  typescript: "5.0.4"
  zod: "3.24.1"
  uuid: "10.0.0"
  testing:
    jest: 29.6.2
    react-testing-library: 14.0.0
  build:
    esbuild: 0.19.0
workspaces:
  packages:
    - "packages/*"
registry:
  path: ~/.syndicate/registry

# API Routing + OpenAPI Forge v3.1
api:
  basePath: /api
  version: 1.3.0
  openapi:
    output: ./docs/08-api-reference/openapi.yaml
    title: Syndicate Dashboard API
    description: Bun-powered, YAML-governed, grep-first REST + WS
    servers:
      - url: https://api.syndicate.gov
        description: Production Vault
      - url: ws://localhost:3003
        description: Local WS Broadcast
  docs:
    enabled: true
    path: /_docs        # Swagger UI
    redoc: /_redoc      # ReDoc (optional)
    openapi: /openapi.yaml
  routes:
    - path: /config/{hash}
      method: GET
      id: get-config-by-hash
      handler: ./routes/config/get-by-hash.ts
      auth: vault
      response:
        200:
          schema: ConfigResponse
          example: { hash: "abc123", data: "!encrypted ${VAULT:api/main}" }
        404: { schema: Error }
      tags: [config, yaml]
      summary: Retrieve interpolated YAML by hash
      sourcemap: true

    - path: /config/store
      method: POST
      id: store-yaml-config
      handler: ./routes/config/store.ts
      auth: csrf+vault
      request:
        schema: StoreRequest
        required: true
      response:
        201: { schema: StoreResponse }
      tags: [config, write]
      summary: Store YAML with auto-interpolation & zstd
      sourcemap: true

    - path: /ws/config-update
      method: WS
      id: ws-live-config
      handler: ./routes/ws/config-broadcast.ts
      auth: csrf
      subprotocol: dashboard-v1.3
      tags: [realtime, ws]
      summary: Live YAML diff stream with permessage-deflate
      sourcemap: true

    - path: /config/validate
      method: POST
      id: validate-yaml-schema
      handler: ./routes/config/validate.ts
      auth: csrf
      request: { schema: YAMLString }
      response:
        200: { schema: ValidationResult }
        400: { schema: ValidationError }
      tags: [config, validate]
      summary: Schema-check YAML before store
      sourcemap: true

    - path: /wand/{action}
      method: GET
      id: wand-admin-actions
      handler: ./routes/wand.ts
      auth: admin
      response:
        200: { schema: WandResponse }
        401: { schema: Error }
        404: { schema: Error }
      tags: [admin, wand]
      summary: Admin wand: reload, diff, rollback
      sourcemap: true

    # Manager Tools API Routes (based on real-world patterns)
    - path: /api/v3/manager-tools/signin
      method: POST
      id: manager-tools-signin
      handler: ./routes/manager-tools/signin.ts
      auth: public
      request:
        schema: SignInRequest
        required: true
      response:
        200: { schema: AuthResponse }
        401: { schema: Error }
      tags: [auth, manager-tools]
      summary: Manager tools authentication endpoint
      sourcemap: true

    - path: /api/v3/manager-tools/common
      method: GET
      id: manager-tools-common
      handler: ./routes/manager-tools/common.ts
      auth: jwt
      response:
        200: { schema: CommonDataResponse }
        401: { schema: Error }
      tags: [manager-tools, common]
      summary: Common manager tools data
      sourcemap: true

    - path: /live/data
      method: GET
      id: live-data-feed
      handler: ./routes/live/data.ts
      auth: jwt
      parameters:
        - name: countries
          in: query
          schema: { type: boolean }
        - name: leagues
          in: query
          schema: { type: boolean }
        - name: sports
          in: query
          schema: { type: boolean }
      response:
        200: { schema: LiveDataResponse }
        401: { schema: Error }
      tags: [live, data, real-time]
      summary: Real-time sports data feed
      sourcemap: true

    - path: /manager-tools/usersList
      method: GET
      id: users-list
      handler: ./routes/manager-tools/usersList.ts
      auth: jwt
      parameters:
        - name: includeSubAgents
          in: query
          schema: { type: boolean }
        - name: agentNames
          in: query
          schema: { type: string }
      response:
        200: { schema: UsersListResponse }
        401: { schema: Error }
      tags: [manager-tools, users]
      summary: List users and agents
      sourcemap: true

    - path: /manager-tools/partnerPreferences
      method: GET
      id: partner-preferences
      handler: ./routes/manager-tools/partnerPreferences.ts
      auth: jwt
      response:
        200: { schema: PartnerPreferencesResponse }
        401: { schema: Error }
      tags: [manager-tools, preferences]
      summary: Partner configuration preferences
      sourcemap: true

    - path: /manager-tools/groups
      method: GET
      id: groups-list
      handler: ./routes/manager-tools/groups.ts
      auth: jwt
      response:
        200: { schema: GroupsResponse }
        401: { schema: Error }
      tags: [manager-tools, groups]
      summary: User groups management
      sourcemap: true

    - path: /manager-tools/agents
      method: GET
      id: agents-list
      handler: ./routes/manager-tools/agents.ts
      auth: jwt
      parameters:
        - name: name
          in: query
          schema: { type: string }
      response:
        200: { schema: AgentsResponse }
        401: { schema: Error }
      tags: [manager-tools, agents]
      summary: Agents management
      sourcemap: true

    - path: /manager-tools/liveEvents
      method: GET
      id: live-events
      handler: ./routes/manager-tools/liveEvents.ts
      auth: jwt
      response:
        200: { schema: LiveEventsResponse }
        401: { schema: Error }
      tags: [manager-tools, live, events]
      summary: Live events management
      sourcemap: true

    - path: /manager-tools/reports/periods
      method: GET
      id: reports-periods
      handler: ./routes/manager-tools/reports/periods.ts
      auth: jwt
      response:
        200: { schema: ReportsPeriodsResponse }
        401: { schema: Error }
      tags: [manager-tools, reports]
      summary: Periodic reports data
      sourcemap: true

    - path: /betLobbyV2/logic
      method: GET
      id: bet-lobby-logic
      handler: ./routes/betLobbyV2/logic.ts
      auth: jwt
      response:
        200: { schema: BetLobbyLogicResponse }
        401: { schema: Error }
      tags: [betting, lobby, logic]
      summary: Betting lobby business logic
      sourcemap: true

    # WebSocket Routes for Real-time Features
    - path: /ws/live-events
      method: WS
      id: ws-live-events
      handler: ./routes/ws/live-events.ts
      auth: jwt
      subprotocol: live-events-v1
      tags: [websocket, live, real-time]
      summary: Real-time live events stream
      sourcemap: true

    - path: /ws/betting-updates
      method: WS
      id: ws-betting-updates
      handler: ./routes/ws/betting-updates.ts
      auth: jwt
      subprotocol: betting-v1
      tags: [websocket, betting, real-time]
      summary: Real-time betting odds and updates
      sourcemap: true

    - path: /ws/manager-notifications
      method: WS
      id: ws-manager-notifications
      handler: ./routes/ws/manager-notifications.ts
      auth: jwt
      subprotocol: notifications-v1
      tags: [websocket, manager, notifications]
      summary: Manager notifications and alerts
      sourcemap: true

    - path: /api/live-events
      method: GET
      id: live-events-api
      handler: ./routes/api/live-events.ts
      auth: public  # Temporarily public for testing, should be jwt
      parameters:
        - name: format
          in: query
          schema: { type: boolean }
        - name: markets
          in: query
          schema: { type: boolean }
        - name: scores
          in: query
          schema: { type: boolean }
      response:
        200: { schema: LiveEventsAPIResponse }
        500: { schema: Error }
      tags: [api, live-events, betting]
      summary: Live betting events data from external platform
      sourcemap: true

    - path: /api/ajax-actions
      method: POST
      id: ajax-actions-api
      handler: ./routes/api/ajax-actions.ts
      auth: public  # Temporarily public for testing, should be jwt
      request:
        schema: AjaxActionRequest
        required: true
      response:
        200: { schema: AjaxActionResponse }
        500: { schema: Error }
      tags: [api, ajax, betting]
      summary: AJAX betting actions (getBetReport, etc.) from external platform
      sourcemap: true

    # Unified SQL API Routes
    - path: /api/sql/query
      method: POST
      id: unified-sql-query
      handler: ./routes/sql/query.ts
      auth: jwt
      request:
        schema: SQLQueryRequest
        required: true
      response:
        200: { schema: SQLQueryResponse }
        401: { schema: Error }
        500: { schema: SQLError }
      tags: [sql, database, unified]
      summary: Unified SQL query endpoint
      sourcemap: true

    - path: /api/sql/users
      method: GET
      id: sql-users-list
      handler: ./routes/sql/users.ts
      auth: jwt
      parameters:
        - name: limit
          in: query
          schema: { type: number }
        - name: offset
          in: query
          schema: { type: number }
      response:
        200: { schema: SQLUsersResponse }
        401: { schema: Error }
      tags: [sql, users, database]
      summary: SQL-based user listing
      sourcemap: true

    - path: /api/sql/analytics
      method: GET
      id: sql-analytics
      handler: ./routes/sql/analytics.ts
      auth: jwt
      parameters:
        - name: startDate
          in: query
          schema: { type: string, format: date }
        - name: endDate
          in: query
          schema: { type: string, format: date }
      response:
        200: { schema: SQLAnalyticsResponse }
        401: { schema: Error }
      tags: [sql, analytics, reports]
      summary: SQL analytics and reporting
      sourcemap: true

    - path: /api/sql/health
      method: GET
      id: sql-health-check
      handler: ./routes/sql/health.ts
      auth: jwt
      response:
        200: { schema: SQLHealthResponse }
        401: { schema: Error }
      tags: [sql, health, monitoring]
      summary: Database health and performance metrics
      sourcemap: true

# Enhanced Authentication & Security Configuration
security:
  scanner: "@socketsecurity/bun-security-scanner"
  minimumReleaseAge: 604800
  
  # JWT Cookie Authentication
  jwt:
    enabled: true
    secret: "${JWT_SECRET}"
    algorithm: "HS256"
    expiresIn: "24h"
    refreshExpiresIn: "7d"
    issuer: "citadel.syndicate.gov"
    audience: "citadel-users"
    
  # Secure Cookie Configuration
  cookies:
    secure: "${COOKIE_SECURE:true}"
    httpOnly: true
    sameSite: "strict"
    domain: "${COOKIE_DOMAIN:localhost}"
    path: "/"
    maxAge: 604800  # 7 days
    
  # Google OAuth2 Configuration
  google:
    enabled: true
    clientId: "${GOOGLE_CLIENT_ID}"
    clientSecret: "${GOOGLE_CLIENT_SECRET}"
    redirectUri: "${GOOGLE_REDIRECT_URI:http://localhost:3000/auth/google/callback}"
    scope: ["openid", "profile", "email"]
    
  # Session Management
  session:
    enabled: true
    store: "redis"  # redis, memory, database
    ttl: 86400  # 24 hours
    secret: "${SESSION_SECRET}"
    rolling: true
    saveUninitialized: false
    
  # Multi-Provider Authentication
  providers:
    jwt:
      enabled: true
      priority: 1
      endpoints:
        login: "/api/auth/login"
        refresh: "/api/auth/refresh"
        logout: "/api/auth/logout"
        
    google:
      enabled: true
      priority: 2
      endpoints:
        login: "/api/auth/google"
        callback: "/api/auth/google/callback"
        logout: "/api/auth/google/logout"
        
    basic:
      enabled: false
      priority: 3
      endpoints:
        login: "/api/auth/basic/login"
        
  # CORS Configuration for Auth Endpoints
  cors:
    enabled: true
    origins: 
      - "${FRONTEND_URL:http://localhost:3000}"
      - "${DASHBOARD_URL:http://localhost:3001}"
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowedHeaders: ["Content-Type", "Authorization", "X-Requested-With"]
    credentials: true
    
  # Performance & Network Optimization
  network:
    # DNS Prefetching
    dns:
      prefetch:
        enabled: true
        hosts:
          - "${API_HOST:localhost}"
          - "${REDIS_HOST:localhost}"
          - "accounts.google.com"
          - "oauth2.googleapis.com"
          - "www.googleapis.com"
        ttl: 30000  # 30 seconds
        
      # DNS Caching
      cache:
        enabled: true
        ttl: 30000  # 30 seconds
        maxSize: 1000
        
    # Connection Pooling & Keep-Alive
    connections:
      keepAlive: true
      maxSimultaneous: "${BUN_CONFIG_MAX_HTTP_REQUESTS:256}"
      timeout: 30000
      reuse: true
      
    # Preconnect Configuration
    preconnect:
      enabled: true
      hosts:
        - "${API_URL:http://localhost:8080}"
        - "${REDIS_HOST:localhost}:6379"
        - "https://accounts.google.com"
        - "https://oauth2.googleapis.com"
      startup: true
      
    # Response Buffering
    buffering:
      enabled: true
      maxResponseSize: "10MB"
      compression: true
      compressionTypes: ["text/*", "application/json", "application/xml"]
      
    # Fetch Optimization
    fetch:
      # Data URL Support
      dataUrls:
        enabled: true
        maxSize: "1MB"
        allowedTypes: ["text/plain", "application/json", "image/*"]
        
      # Blob URL Support
      blobUrls:
        enabled: true
        maxSize: "5MB"
        cleanupInterval: 300000  # 5 minutes
        
      # Debugging
      verbose: "${FETCH_VERBOSE:false}"
      
      # Error Handling
      errorHandling:
        rejectUnauthorized: true
        timeout: 30000
        retries: 3
        retryDelay: 1000

# Bun Runtime Configuration
bun:
  # Default CLI Arguments
  options:
    # Development defaults
    development: "--watch --hot --verbose"
    # Production defaults  
    production: "--optimize --minify"
    # Testing defaults
    testing: "--coverage --reporter=verbose"
    
  # Custom User-Agent
  userAgent:
    default: "Citadel/${APP_VERSION:3.0.0} (Bun-${BUN_VERSION:1.3.0})"
    fetch: "Citadel-Fetch/${APP_VERSION:3.0.0}"
    auth: "Citadel-Auth/${APP_VERSION:3.0.0}"
    
  # Preload Scripts
  preload:
    enabled: true
    scripts:
      - "./scripts/preload/setup.ts"
      - "./scripts/preload/database.ts"
      - "./scripts/preload/auth.ts"
    environment: "BUN_INSPECT_PRELOAD"
    
  # SQL Optimization
  sql:
    # PostgreSQL preconnect at startup
    preconnect:
      enabled: true
      databaseUrl: "${DATABASE_URL}"
      flag: "--sql-preconnect"
      
    # Connection pooling
    pool:
      min: 2
      max: 10
      idleTimeout: 30000
      
  # Standalone Executable Control
  standalone:
    # BUN_BE_BUN environment variable for compiled executables
    beBun:
      enabled: true
      description: "Run Bun binary instead of embedded entry point"
      usage: "BUN_BE_BUN=1 ./myapp --version"
      
  # Performance Optimizations
  performance:
    # Memory management
    memory:
      maxHeap: "2GB"
      gcThreshold: 0.8
      
    # Threading
    threads:
      max: "${BUN_MAX_THREADS:4}"
      workerPool: true
      
    # Compilation cache
    cache:
      enabled: true
      directory: "./.bun/cache"
      maxSize: "500MB"
rules:
  header:
    schema:
      scope:
        - GOV
        - SEC
        - OPS
        - ALERT
        - BASH
        - DASHBOARD
        - ETL
      type:
        - RULES
        - SCRIPT
        - CONFIG
        - MULTI-ETL
      variant:
        - EXPANDED
        - COMPACT
        - LIVE
        - DEV
        - TEST
        - DEPRECATED
        - SCRIPT
        - YAML
      id:
        pattern: '^[A-Z]{3,4}-[A-Z0-9-]{4,12}-[0-9]{3}$'
      version:
        semver: '^v[0-9]+\.[0-9]+\.[0-9]+$|^v[0-9]+\.[0-9]+$'
      status:
        - LIVE
        - DEV
        - TEST
        - DEPRECATED
        - REQUIRED
        - STANDARD
        - OPTIONAL
    defaults:
      scope: GOV
      type: RULES
      variant: ''
      version: v2.9
      status: ACTIVE
    grep:
      patterns:
        all-tags: '\[[a-z0-9.-]+\]'
        by-scope: '\[GOV\-[A-Z]+\-[A-Z+\-'
        required-only: '\[.*REQUIRED\]'
      flags:
        - '--type-add'
        - 'sh:*.sh'
        - '--type-add'
        - 'yaml:*.yaml'
        - '--type-add'
        - 'yml:*.yml'
        - '--smart-case'
        - '--hidden'
        - '-g'
        - '!node_modules/**'
        - '-g'
        - '!.git/**'
        - '-g'
        - '!dist/**'
        - '-g'
        - '!.citadel/indexes/.tags.index'
        - '--colors'
        - 'match:fg:green'
        - '--colors'
        - 'line:fg:yellow'
        - '--colors'
        - 'path:fg:blue'
        - '--max-columns'
        - '150'
        - '--max-columns-preview'
    rg-flags: '--type md --no-heading --with-filename --colors match:fg:yellow:style:bold'
  validate:
    hooks:
      - parse-headers: true
      - grep-index: true

# AI Route Suggester Configuration
ai:
  suggester:
    enabled: true
    cron: '0 3 * * *'          # 03:00 UTC – zero-traffic window
    logGlob: ./logs/access.sample.ndjson
    minConfidence: 0.88        # cosine similarity vs existing routes
    maxNewPerRun: 5            # guardrail – no blast radius
    autoPR: true               # opens PR, does NOT merge
    commitMsg: 'feat(ai): suggested routes from ${{ .runId }}'
