# Minimal bun.yaml for testing
catalog:
  react: "18.3.1"
  typescript: "5.0.4"

api:
  basePath: /api
  version: 1.3.0
  docs:
    enabled: true
    path: /_docs
  routes:
    - path: /test
      method: GET
      id: test-route
      handler: ./routes/test.ts

ai:
  suggester:
    enabled: true
    logGlob: ./logs/access.sample.ndjson
    minConfidence: 0.88
    maxNewPerRun: 5
