name: citadel-ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0
          node-version: ${{ matrix.node }}
      
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      
      - name: Start Citadel Server
        run: bun run ci &
      
      - name: Wait for Server
        run: sleep 2
      
      - name: Run Citadel CI Gate
        run: |
          bun test --smol --coverage --bail=3 --rerun-each=5 --randomize --seed=${{ github.run_id }}
        env:
          CLAUDECODE: ${{ github.actor == 'claude-code' && '1' || '0' }}
      
      - name: Enhanced Runtime Checks
        run: |
          bun test ./tests/tz-matrix.test.ts
          bun test ./tests/memory.test.ts ./tests/async-leak.test.ts ./tests/sourcemap.test.ts
      
      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: junit-node-${{ matrix.node }}
          path: bun.xml
      
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-node-${{ matrix.node }}
          path: coverage/lcov.info
      
      - name: Generate Coverage Badge
        run: |
          COVERAGE=$(grep -oP 'Lines:\s+\K\d+' coverage/lcov.info | head -1)
          curl -s "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen" > badge.svg
      
      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: badge.svg
      
      - name: Stop Server
        run: pkill -f "bun run ci" || true
